### ISSUE TITLE
Eagle CAM 4 layer v7 missing copper 3

### ISSUE THREAD

**Issue by brian-mccarter** [MacroFab/EDALibraries#11]
The CAM job `Eagle/CAM/MF_4_Layer_V7.cam`, section `Middle Copper Layer 3` does not have layer `3` selected for output.

I am using Eagle 7.7.0 on Linux.

**Comment by LonghornEngineer** [comment]
Default for 4 Layer boards in eagle is Layers 1,2,15,16.
