### ISSUE TITLE
EAGLE devices lose values during library updates or package changes.

### ISSUE THREAD

**Issue by PML-Trey** [MacroFab/EDALibraries#16]
Due to the blank Value attribute of the parts in the EAGLE libraries, part lose user assigned values when libraries are updated or packages are changed.  Please refer to this Autodesk forum post for more information:
[https://forums.autodesk.com/t5/eagle-forum/package-library-updates-remove-assigned-values/m-p/8202639](https://forums.autodesk.com/t5/eagle-forum/package-library-updates-remove-assigned-values/m-p/8202639)

**Comment by LonghornEngineer** [comment]
I just pushed a change that removes the "Value" attribute in the Eagle Libraries
