### ISSUE TITLE
MF_Eagle_Placement.ulp does not output Populate and MPN fields

### ISSUE THREAD

**Issue by randvoorhies** [MacroFab/EDALibraries#3]
The MF_Eagle_Placement.ulp script does not output the `Populate` and `MPN` fields necessary to fill the MPN field of the BOM.  I have a quick fix to do this, and can submit a pull request if you want.

**Comment by LonghornEngineer** [comment]
Hi randvoorhies. Thanks for bringing this up. I will work on the ULP on Monday as it has some bug fixes and I will add in the Populate and MPN fields.

**Comment by randvoorhies** [comment]
Great! Is this the same script you guys are running on your backend? If so, that would explain why just importing my `.sch` and `.brd` files doesn't automatically populate the MPN field in the BOM.

**Comment by LonghornEngineer** [comment]
Correct! Sorry for the delay on fixing this :D

**Comment by LonghornEngineer** [comment]
Randvoorhies. I just pushed a fix to the ULP that addresses the MPN and Populate fields. To use them add an attribute to your part call MPN and then for the value add in the part number you want to use. Populate works the same way. If your part does not have a populate attribute it will default to populate by setting the field to 1. A 0 indicates non populate.
