### ISSUE TITLE
KiCad Schematic Symbols

### ISSUE THREAD

**Issue by gregasmaximus** [MacroFab/EDALibraries#4]
I see the footprints but will you provide the schematic symbols as well? I'd like to start a new design using your house parts. Thanks!

**Comment by LonghornEngineer** [comment]
Hey Greg. Yup we are working on them this coming week!

**Comment by gregasmaximus** [comment]
Cool, thanks for the update!

**Comment by gregasmaximus** [comment]
Closed by commit ca480c7780dae51252e32210768d29fc1e407e39
