### ISSUE TITLE
KiCad component value text on wrong layer

### ISSUE THREAD

**Issue by gregasmaximus** [MacroFab/EDALibraries#5]
In the default KiCad footprint libraries the text of the component value is on layer F.Fab. In the macrofab libraries, the component value is on layer F.SilkS.

Often we don't want component values on the silkcreen...it gets way too busy. Putting the values on a separate layer (as is the default in the KiCad footprint libraries) makes it much easier to manage visibility. In my case, I discovered this after uploading my file to macrofab and had to manually change the layer on each component.

PS...thanks for supplying components and footprints!

**Comment by LonghornEngineer** [comment]
Hi Gregasmaximus! Thanks for bringing this up. We currently don't have anyone that uses KiCad on a daily basis here at MacroFab so at the moment I can't really fix this problem.

**Comment by slegge** [comment]
I'll take a look at this

**Comment by slegge** [comment]
Submitted PR#9 (https://github.com/MacroFab/EDALibraries/pull/9)

**Comment by LonghornEngineer** [comment]
Looks good! Thanks :)
